package com.quan.exercise;

public class E12 {
	public static void main(String[] args) {
		int i = -1 << 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
		i >>>= 1;
		System.out.println(Integer.toBinaryString(i));
	}
}